apiVersion: apps/v1
kind: Deployment
metadata:
  name: mev-inspect-deployment
  labels:
    app: mev-inspect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mev-inspect
  template:
    metadata:
      labels:
        app: mev-inspect
    spec:
      containers:
      - name: mev-inspect
        image: mev-inspect-py
        command: [ "/app/entrypoint.sh" ]
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mev-inspect-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mev-inspect-db-credentials
              key: password
        - name: POSTGRES_HOST
          value: postgresql
        - name: RPC_URL
          valueFrom:
            configMapKeyRef:
              name: mev-inspect-rpc
              key: url
        livenessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 20
          periodSeconds: 5
